name: CI for HTML Project

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on PRs to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use a Linux-based environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # You can specify the version you need

      - name: Install Dependencies (if any)
        run: |
          npm install

      - name: Lint HTML and CSS
        run: |
          npm install -g htmlhint stylelint
          htmlhint **/*.html
          stylelint "**/*.css"

      - name: Deploy to GitHub Pages (Optional)
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin main

      - name: End the Job
        run: echo "CI Process Finished"
